### ISSUE TITLE
Support for Multiverse-Core worlds

### ISSUE THREAD

**Issue by klugemonkey** [Roytreo28/Revenge#6]
Multiverse worlds seem to be getting loaded after Revenge checks the disable-worlds field in the config file.   Should probably make sure that worlds that are added by Multiverse-Core work with Revenge, since it's a very popular plugin.

**Comment by Royalphax** [comment]
No problem, will be fixed !

**Comment by SlimeDog** [comment]
So now the disabled-world list is processed twice. Why not just make Multiverse-Core (and any other multiworld plugins Revenge recognizes) a soft dependency, so Revenge waits to load until after MV?

**Comment by Royalphax** [comment]
Well, why not try this. But as loading the disabled-worlds not taking a lot of RAM, I will wait the next big update to do this.

**Comment by SlimeDog** [comment]
Yes, not a big deal. Just cleaner.

**Comment by SlimeDog** [comment]
IMHO, the issue should not be closed until a fix is released.
