### ISSUE TITLE
1.15 Support

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [Roytreo28/Revenge#8]
Hi <3
Could you add 1.15 support? :D

**Comment by laer26** [comment]
please update 1.15 i love plugin :3

**Comment by Royalphax** [comment]
Hello guys, It's on my TODO list, I will update the plugin for 1.15 but for now I can't because I'have to deal with my premium plugins ...
Revenge's code is on Github so any other developer can add 1.15 support by submitting a merge request :)
